version: 2.1

setup: true

orbs:
  continuation: circleci/continuation@1.0.0

jobs:
  setup:
    docker:
      - image: cimg/python:3.10
    steps:
      - checkout
      - run:
          name: Install pci-guard deps
          command: pip install --user -r requirements.txt
      - run:
          name: Set up PATH
          command: |
            echo 'export PATH=$HOME/bin:$PATH' >> $BASH_ENV
            mkdir -p $HOME/bin
      - run:
          name: Install OPA
          command: |
            curl -L -o $HOME/bin/opa https://openpolicyagent.org/downloads/v0.65.0/opa_linux_amd64_static
            chmod +x $HOME/bin/opa
      - run:
          name: Install Trivy
          command: |
            curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b $HOME/bin v0.70.0
      - run:
          name: Clone external targets
          command: |
            git clone https://github.com/hemantdeshwal19/payment-fraud-detection.git \
              /tmp/targets/payment-fraud-detection
            cd /tmp/targets/payment-fraud-detection
            git checkout 31dc1746ee51f3dbee0fc8f54ee186341fc328ff
            cd -
      - run:
          name: Detect stacks and generate continuation config
          command: |
            python3 .circleci/generate_config.py \
              --targets \
                "pci-guard:." \
                "payment-fraud-detection:/tmp/targets/payment-fraud-detection" \
              --output /tmp/continuation.yml
      - run:
          name: Preview generated config
          command: cat /tmp/continuation.yml
      - continuation/continue:
          configuration_path: /tmp/continuation.yml

workflows:
  setup-workflow:
    jobs:
      - setup
