version: 2.1

setup: true

orbs:
  continuation: circleci/continuation@1.0.0

jobs:
  setup:
    docker:
      - image: cimg/python:3.10
    steps:
      - checkout
      - restore_cache:
          keys:
            - pip-deps-v1-{{ checksum "requirements.txt" }}
      - run:
          name: Install pci-guard deps
          command: pip install --user -r requirements.txt
      - save_cache:
          key: pip-deps-v1-{{ checksum "requirements.txt" }}
          paths:
            - ~/.local/lib/python3.10/site-packages
            - ~/.local/bin
      - run:
          name: Set up PATH
          command: |
            echo 'export PATH=$HOME/bin:$PATH' >> $BASH_ENV
            mkdir -p $HOME/bin
      - restore_cache:
          keys:
            - opa-v0.65.0
      - run:
          name: Install OPA
          command: |
            if [ ! -f $HOME/bin/opa ]; then
              curl -L -o $HOME/bin/opa https://openpolicyagent.org/downloads/v0.65.0/opa_linux_amd64_static
              chmod +x $HOME/bin/opa
            fi
      - save_cache:
          key: opa-v0.65.0
          paths:
            - ~/.local/bin/opa
      - restore_cache:
          keys:
            - trivy-v0.70.0
      - run:
          name: Install Trivy
          command: |
            if [ ! -f $HOME/bin/trivy ]; then
              curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b $HOME/bin v0.70.0
            fi
      - save_cache:
          key: trivy-v0.70.0
          paths:
            - ~/.local/bin/trivy
      - run:
          name: Clone external targets
          command: |
            git clone https://github.com/hemantdeshwal19/payment-fraud-detection.git \
              /tmp/targets/payment-fraud-detection
            cd /tmp/targets/payment-fraud-detection
            git checkout 31dc1746ee51f3dbee0fc8f54ee186341fc328ff
            cd -
      - run:
          name: Detect stacks and generate continuation config
          command: |
            python3 .circleci/generate_config.py \
              --targets \
                "pci-guard:." \
                "payment-fraud-detection:/tmp/targets/payment-fraud-detection" \
              --output /tmp/continuation.yml
      - run:
          name: Preview generated config
          command: cat /tmp/continuation.yml
      - run:
          name: Install CircleCI CLI
          command: |
            curl -fLSs https://raw.githubusercontent.com/CircleCI-Public/circleci-cli/main/install.sh | sudo bash
            circleci version
      - run:
          name: Validate generated config
          command: circleci config validate /tmp/continuation.yml
      - continuation/continue:
          configuration_path: /tmp/continuation.yml

workflows:
  setup-workflow:
    jobs:
      - setup
